hsize = 2000
ssize = 20
t = 1000.0
dt = 0.02
runs = 1000
trel = 0.0
threads = 40
tau = 0.5
lambda = 1.0
hfield = [0.0, 0.0, 0.0]
hs = [0.0, 0.0, 0.0]
jvar = 0.02
hvar = 0.0
method = 2
ednsty = -0.66
file = "log"
strob = true
offset = 8000
beta = 2.8889029604295944
mc_points = 1000
e = 0.9
drive = "xyplane"
log = true
