hsize = 2000
ssize = 40
t = 2000.0
dt = 0.02
runs = 16000
trel = 0.0
threads = 80
tau = 0.5
lambda = 1.0
hfield = [0.0, 0.0, 0.0]
hs = [0.0, 0.0, 0.0]
jvar = 0.001
hvar = 0.0
method = 2
ednsty = -0.66
file = "log"
strob = false
offset = 74208
beta = 2.8889029604295944
mc_points = 32000
e = 0.999
drive = "xyplane"
log = false
