hsize = 20
ssize = 20
t = 3200.0
dt = 0.05
runs = 1000
trel = 0.0
threads = 12
tau = 1.6
lambda = 1.0
hfield = [0.0, 0.0, 0.0]
hs = [0.0, 0.0, 0.0]
jvar = 0.03
hvar = 0.0
method = 2
ednsty = -0.66
file = "log"
strob = true
offset = 1000
beta = 2.8889029604295944
mc_points = 1000
e = 0.9
drive = "xyplane"
log = true
