hsize = 40
ssize = 40
t = 256.0
dt = 0.02
runs = 2
trel = 0.0
threads = 8
tau = 10.0
lambda = 1.0
hfield = [0.0, 0.0, -1.5707963267948966]
hs = [1.0, 0.0, 0.0]
jvar = 0.001
hvar = 0.0
method = 2
ednsty = -0.18
file = "log"
strob = false
offset = 0
beta = 10
mc_points = 256000
e = 0.999
drive = "staticfield"
log = true
