hsize = 2000
ssize = 40
t = 256.0
dt = 0.02
runs = 2
trel = 0.0
threads = 2
tau = 10.0
lambda = 1.0
hfield = [0.0, 0.0, 0.0]
hs = [0.0, 0.0, 0.0]
jvar = 0.001
hvar = 0.0
method = 2
ednsty = -0.66
file = "log"
strob = false
offset = 0
beta = 2.88
mc_points = 1000
e = 0.9
drive = "xyplane"
log = true
