hsize = 2000
ssize = 40
t = 5000.0
dt = 0.001
runs = 26
trel = 0.0
threads = 12
tau = 0.5
lambda = 1.0
hfield = [0.0, 0.0, 0.0]
hs = [0.0, 0.0, 0.0]
jvar = 0.02
hvar = 0.0
method = 2
ednsty = -0.66
file = "log"
strob = true
offset = 734
beta = 2.8889029604295944
mc_points = 1000
e = 0.9
drive = "xyplane"
log = true
